### ISSUE TITLE
[bug] System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by GetcuReone** [GetcuReone/FactFactory#367]
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
  Stack Trace:
      at GetcuReone.FactFactory.Versioned.VersionedFactFactoryHelper.CompareByVersion(IFactRule firstRule, IFactRule secondRule, IWantActionContext context)
   at GetcuReone.FactFactory.Versioned.Facades.SingleEntityOperations.VersionedSingleEntityOperationsFacade.CompareFactRules(IFactRule firstRule, IFactRule secondRule, IWantActionContext context)
   at GetcuReone.FactFactory.Facades.SingleEntityOperations.SingleEntityOperationsFacade.<>c__DisplayClass0_0.<GetRuleComparer>b__0(IFactRule x, IFactRule y)
   at System.Collections.Generic.ComparisonComparer`1.Compare(T x, T y)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Collections.Generic.ComparisonComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, Comparison`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)

**Comment by GetcuReone** [comment]
I use the following facts:

```
public sealed class CustomVersion : BaseIntVersion
{
    public CustomVersion(int version) : base(version) { }
}

public sealed class Version1 : BaseIntVersion
{
    public Version1() : base(1) { }
}

internal sealed class TestObj_HashCode : BaseFact<long>
{
    public TestObj_HashCode (long value) : base(value) { }
}

internal sealed class TestObj: BaseFact<object>
{
    public TestObj(object value) : base(value) { }
}
```
The next rule signature:

```
(Version1 v, TestObj obj) =>
{
    return new TestObj_HashCode(1);
}
```

Making the next call:

```
var container = new FactContainer
{
    new TestObj(new object()),
    new CustomVersion(1),
    new Version1(),
};

factory.DeriveFact<TestObj_HashCode , CustomVersion>(container);
```

**Comment by GetcuReone** [comment]
You can't use versioning like that. Let the types of facts and be different, but their meaning is the same. Therefore, the factory works out unexpectedly
